import React from "react";

export default function Head(props){
    return(
        <React.Fragment>
            <title>{props.title}</title>
            <meta content="width=device-width, initial-scale=1" name="viewport"/>
            <meta name="desription" content="Generated by create next app"/>
            <link rel="icon" href="/icons/favicon.ico"/>
        </React.Fragment>
    )
}